
- id: smooth_wake_up
  alias: 'Smooth Wake Up'
  initial_state: true
  trigger:
    - platform: template
      value_template: >-
        {% set alarm_time = states('sensor.sm_s926b_next_alarm') %}
        {% if alarm_time not in  ['unavailable', 'none', 'unknown'] %} 
        {{ now() >= alarm_time | as_datetime | as_local - 
          timedelta(minutes=(states.input_number.wake_up_transition_time.state | int)) }}
        {% endif %}
  condition:
    - condition: time
      after: input_datetime.morning_time
      before: input_datetime.evening_time
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
  action:
    - service: script.wake_up
      data:
        transition: "{{ (states.input_number.wake_up_transition_time.state | int) }}"
    - delay:
        minutes: "{{ (states.input_number.wake_up_transition_time.state | int) }}"
    - service: script.morning_mode

- id: reset_night_mode
  alias: 'Reset Night Mode'
  initial_state: true
  trigger:
    - platform: time
      at: '14:00:00'
  condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.sleep_mode
          state: 'on'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.sleep_mode
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.night_mode

- id: evening_mode
  alias: 'Evening Mode'
  initial_state: true
  trigger:
    platform: time
    at: input_datetime.evening_time
  condition:
    - condition: state
      entity_id: group.persons
      state: "home"
  action:
    - service: 
        script.turn_on_lights_evening

- id: night_mode
  alias: 'Night Mode'
  initial_state: true
  trigger:
    - platform: time
      at: input_datetime.night_time
  condition:
    - condition: state
      entity_id: group.persons
      state: "home"
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    service: 
      script.turn_on_lights_night

- id: hall_motion_sensor_off
  alias: Hall Motion Sensor Off
  description: 'Delayed turning off hall lights after motion sensor previously has been triggered'
  variables:
    current_timestamp: "{{ as_timestamp(now()) - as_timestamp(now().date()) }}"
    evening_timestamp: "{{ states.input_datetime.evening_time.attributes.timestamp }}"
    night_timestamp: "{{ states.input_datetime.night_time.attributes.timestamp }}"
    is_evening: "{{ evening_timestamp <= current_timestamp < night_timestamp }}"
  trigger:
    entity_id: light.closet
    platform: state
    to: 'off'
  action:
    - choose:
      - conditions: "{{ not is_evening }}"
        sequence:
          service: light.turn_off
          target:
            entity_id: light.hall_ceiling

- id: hall_motion_sensor_on
  alias: Hall Motion Sensor On
  description: 'Turn on lights in hall when motion sensor is triggered'
  variables:
    current_timestamp: "{{ as_timestamp(now()) - as_timestamp(now().date()) }}"
    morning_timestamp: "{{ states.input_datetime.morning_time.attributes.timestamp }}"
    evening_timestamp: "{{ states.input_datetime.evening_time.attributes.timestamp }}"
    night_timestamp: "{{ states.input_datetime.night_time.attributes.timestamp }}"
    is_daytime: "{{ morning_timestamp <= current_timestamp < evening_timestamp }}"
    is_evening: "{{ evening_timestamp <= current_timestamp < night_timestamp }}"
  trigger:
    - platform: state
      entity_id: light.closet
      to: 'on'
  condition:
      condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    - choose:
      - conditions: "{{ is_daytime or is_evening }}"
        sequence:
          service: light.turn_on
          target:
            entity_id: light.hall_ceiling

- id: coming_home
  alias: 'Coming home'
  initial_state: true
  variables:
    current_timestamp: "{{ as_timestamp(now()) - as_timestamp(now().date()) }}"
    morning_timestamp: "{{ states.input_datetime.morning_time.attributes.timestamp }}"
    evening_timestamp: "{{ states.input_datetime.evening_time.attributes.timestamp }}"
    night_timestamp: "{{ states.input_datetime.night_time.attributes.timestamp }}"
    is_daytime: "{{ morning_timestamp <= current_timestamp < evening_timestamp }}"
    is_evening: "{{ evening_timestamp <= current_timestamp < night_timestamp }}"
    is_night: "{{ not ( is_daytime or is_evening ) }}"
    is_summer: "{{ is_state('sensor.season', 'summer') }}"
  trigger:
    platform: state
    entity_id: group.persons
    to: "home"
  condition:
    condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
    - service: media_player.turn_on
      target:
        entity_id: media_player.the_frame
    - choose:
      - conditions: "{{ is_daytime }}"
        sequence:
          service: script.turn_on_lights
      - conditions: "{{ is_evening }}"
        sequence:
          service: script.turn_on_lights_evening
      - conditions: "{{ is_night }}"
        sequence:
          service: script.turn_on_lights_night
    - choose:
      - conditions: "{{ is_summer and not is_night }}"
        sequence:
          - service: script.open_covers

- id: leaving_home
  alias: 'Leaving Home'
  initial_state: true
  variables:
    current_timestamp: "{{ as_timestamp(now()) - as_timestamp(now().date()) }}"
    morning_timestamp: "{{ states.input_datetime.morning_time.attributes.timestamp }}"
    evening_timestamp: "{{ states.input_datetime.evening_time.attributes.timestamp }}"
    is_sunny: "{{ is_state('weather.forecast_home', 'sunny' )}}"
    is_daytime: "{{morning_timestamp <= current_timestamp < evening_timestamp }}"
    is_summer: "{{ is_state('sensor.season', 'summer') }}"
  trigger:
    platform: state
    entity_id: group.persons
    to: not_home
  action:
    - service: light.turn_off
      target:
        entity_id: all
    - service: media_player.turn_off
      target:
        entity_id: media_player.the_frame
    - choose:
      - conditions: "{{ is_summer and is_sunny and is_daytime }}"
        sequence:
          service: script.shade_mode

- alias: John bluetooth phone presence
  trigger:
    - platform: numeric_state
      entity_id: sensor.samsung_phone_bluetooth
      above: 50
  action:
    - service: device_tracker.see
      data:
        dev_id: samsung_phone_bluetooth
        location_name: home
        source_type: bluetooth

- alias: John bluetooth smart watch presence
  trigger:
    - platform: numeric_state
      entity_id: sensor.john_smart_watch_bluetooth
      above: 50
  action:
    - service: device_tracker.see
      data:
        dev_id: john_smart_watch_bluetooth
        location_name: home
        source_type: bluetooth

- alias: Natie bluetooth phone presence
  trigger:
    - platform: numeric_state
      entity_id: sensor.natie_phone_bluetooth
      above: 50
  action:
    - service: device_tracker.see
      data:
        dev_id: natie_phone_bluetooth
        location_name: home
        source_type: bluetooth

- alias: Natie bluetooth smart watch presence
  trigger:
    - platform: numeric_state
      entity_id: sensor.natie_smart_watch_bluetooth
      above: 50
  action:
    - service: device_tracker.see
      data:
        dev_id: natie_smart_watch_bluetooth
        location_name: home
        source_type: bluetooth

- alias: John bluetooth phone away
  trigger:
    - platform: numeric_state
      entity_id: sensor.samsung_phone_bluetooth
      below: 50
  action:
    - service: device_tracker.see
      data:
        dev_id: samsung_phone_bluetooth
        location_name: not_home
        source_type: bluetooth

- alias: John bluetooth smart watch away
  trigger:
    - platform: numeric_state
      entity_id: sensor.john_smart_watch_bluetooth
      below: 50
  action:
    - service: device_tracker.see
      data:
        dev_id: john_smart_watch_bluetooth
        location_name: not_home
        source_type: bluetooth

- alias: Natie bluetooth phone away
  trigger:
    - platform: numeric_state
      entity_id: sensor.natie_phone_bluetooth
      below: 50
  action:
    - service: device_tracker.see
      data:
        dev_id: natie_phone_bluetooth
        location_name: not_home
        source_type: bluetooth

- alias: Natie bluetooth smart watch away
  trigger:
    - platform: numeric_state
      entity_id: sensor.natie_smart_watch_bluetooth
      below: 50
  action:
    - service: device_tracker.see
      data:
        dev_id: natie_smart_watch_bluetooth
        location_name: not_home
        source_type: bluetooth
